### ISSUE TITLE
抱歉给大佬留个言，有没有这样的组件demo呢。

### ISSUE THREAD

**Issue by leosin** [bowencool/create-vitepress-demo#6]
vitepress也不支持插件，官方文档更是惜字如金。

抱歉给大佬留个言，有没有这样的组件demo呢。
![image](https://user-images.githubusercontent.com/3676670/193991237-deece2ce-17b0-4b07-afd6-5bc619290355.png)

就是在custom block的基础上，能实现切换内容的。

**Comment by bowencool** [comment]
你说的是不是这个，你可以试一下

![](https://user-images.githubusercontent.com/20217146/193992413-e63e85e7-b89e-4177-ad51-6d021108a78e.png)

**Comment by leosin** [comment]
我刚刚又找到了一个帖子，原来是叫code group的，不过好像是还没合并到vitepress里。
https://github.com/vuejs/vitepress/pull/1242
我去学习一下。

**Comment by Zhengqbbb** [comment]
Demo:  https://cz-git.qbb.sh/guide/#step-1-install-dependencies
Source code: https://github.com/Zhengqbbb/cz-git/tree/main/docs/.vitepress/theme/components

你可以看看，我借鉴了vuepress-next，vitepress 提倡 最小化，除非在md插件中有所突破，否则不会在短期内使用vue组件轻易支持

**Comment by leosin** [comment]
太帅了，就是这个，赶紧学习一下 多谢🙏 @Zhengqbbb
